homework33/store/game_store/urls.py
from django.urls import path

from . import views


app_name = 'game'
urlpatterns = [
    path('', views.games_all, name='games'),
    path('category/', views.all_categories, name='all_categories'),
    path('sorting/', views.sorting, name='sorting'),
    path('category/<slug:category_slug>/', views.category_games, name='category_games'),
    path('search-games', views.search_games, name='search-games'),
    path('<slug:game_slug>/comment/', views.CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('<slug:game_slug>/', views.every_game, name='game_slug'),
]

homework33/store/game_store/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator
from django.db.models import Avg
from django.urls import reverse_lazy

import datetime   

from .models import Game, Category, Comment
from .forms import CommentForm


def games_all(request):
    games = Game.objects.filter(is_active=True).select_related('category')
    paginator = Paginator(games, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'games/home.html', {'page_obj': page_obj})


@login_required(login_url='user:login')
def every_game(request, game_slug):
    game = get_object_or_404(Game, slug=game_slug)
    comments = game.comments.all().order_by('-pub_date')
    last = request.COOKIES.get(game_slug)
    average_grade = game.comments.aggregate(Avg('grade'))
    session_key = f'{game_slug}_visits'
    visits = request.session.get(session_key, 0)
    visits += 1
    request.session[session_key] = visits
    context = {
        'game': game,
        'comments': comments,
        'last': last,
        'visits': visits,
        'average_grade': average_grade['grade__avg'],
    }
    response = render(request, 'games/game.html', context=context)
    visit_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    response.set_cookie(game_slug, visit_time)
    return response


@cache_page(60 * 5)
def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'category/all_categories.html', {'categories': categories})


@login_required(login_url='user:login')
def category_games(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    games = category.game_set.filter(is_active=True, category=category)
    context = {
        'category': category,
        'games': games
    }
    return render(request, 'category/category_games.html', context)


@cache_page(60 * 5)
def sorting(request):
    sort = request.GET.get('sort')  
    sort_order = {
        'name_desc': Game.objects.order_by('-name'),
        'name_asc': Game.objects.order_by('name'),
    }
    games = sort_order.get(sort).select_related('category')
    return render(request, 'sorting/sorting.html', {'games': games})


def search_games(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        games = Game.objects.filter(name__icontains=searched)
        return render(request, 'search/search_games.html', {'searched': searched, 'games': games})
    else:
        return render(request, 'search/search_games.html', {})


class CommentCreateView(CreateView, LoginRequiredMixin):
    template_name = 'comments/comment_create.html'
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.game = Game.objects.get(slug=self.kwargs['game_slug'])
        return super().form_valid(form)


class CommentUpdateView(UpdateView):
    model = Comment
    template_name = 'comments/comment_update.html'
    form_class = CommentForm


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'comments/comment_delete.html'
    success_url = reverse_lazy('game:games')

homework33/store/game_store/templates/category/all_categories.html
{% extends 'game_store/base.html' %}
{% block title %}Categories{% endblock %}

{% block content %}
<br>
{% for category in categories %}
<div class="container">
    <h1 class="fw-light"><a href="{% url 'game:category_games' category_slug=category.slug %}" class="text-info">{{category.name}}</a></h1>
        <h5>Описание:</h5>
        <p>{{category.description|safe}}</p>
        <hr>
</div>
{% endfor %}
{% endblock %}

homework33/store/game_store/templates/category/category_games.html
{% extends 'game_store/base.html' %}
{% block title %}{{category}}{% endblock %}

{% block content %}
<br>
{% for game in games %}
<div class="container">
    <h2 class="fw-light">Жанр: {{category.name}}</h2><br>
    <img class="rounded" style="width: 500px; height: 500px; object-fit: cover;" src={{game.game_image.url}} alt={{game.name}}/>
    <br><br>
    <h5><a href="{% url 'game:game_slug' game_slug=game.slug %}" class="text-info">{{game.name}}</a></h5>
        <ul>
            <li>Цена: {{game.price}} руб</li>
            <li>Дата выхода: {{game.release_date|date:"d F, Y."}}</li>
        </ul>
        <hr>
</div>
{% endfor %}
{% endblock %}