homework30/store/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('games/', views.GameList.as_view()),
]

homework30/store/game_store/urls.py
from django.urls import path

from . import views


app_name = 'game'
urlpatterns = [
    path('', views.games_all, name='games'),
    path('category/', views.all_categories, name='all_categories'),
    path('sort-alphab/', views.sorting_in_alphabetical_order, name='sort_alphab'),
    path('sort-not-alphab/', views.sorting_not_in_alphabetical_order, name='sort_not_alphab'),
    path('category/<slug:category_slug>/', views.category_games, name='category_games'),
    path('search-games', views.search_games, name='search-games'),
    path('<slug:game_slug>/comment/', views.CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('<slug:game_slug>/', views.every_game, name='game_slug'),
]

homework30/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_store.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework30/store/game_store/models.py
from django.db import models
from django.urls import reverse
from decimal import Decimal
from django.contrib.auth.models import User

class ShopInfoMixin(models.Model):
    name = models.CharField('Название', max_length=50, null=True)
    slug = models.SlugField('Индивидуальный ярлык', max_length=25)
    description = models.TextField('Описание')
    is_active = models.BooleanField('Доступен')

    class Meta:
        abstract = True
        indexes = [
            models.Index(fields=['name'], name='%(app_label)s_%(class)s_name_index'),
        ]


class Category(ShopInfoMixin):
    games_amount = models.IntegerField('Колличество игр в категории', default=0)

    def __str__(self):
        return f'{self.name}'


class Game(ShopInfoMixin):
    pub_date = models.DateField('Дата Публикации', auto_now_add=True)
    release_date = models.DateField('Дата Выхода')
    price = models.DecimalField('Цена', max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None)
    game_image = models.ImageField('Изображение Игры', upload_to='game_store/media/games')

    def __str__(self):
        return f'{self.name}'



class Comment(models.Model):
    choices = [
        (Decimal("1.0"), "★☆☆☆☆ (1/5)"),
        (Decimal("2.0"), "★★☆☆☆ (2/5)"),
        (Decimal("3.0"), "★★★☆☆ (3/5)"),
        (Decimal("4.0"), "★★★★☆ (4/5)"),
        (Decimal("5.0"), "★★★★★ (5/5)"),
    ]
    game = models.ForeignKey(Game, blank=True, null=True, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='users')
    text = models.TextField('Комментарий')
    pub_date = models.DateTimeField(auto_now_add=True)
    grade = models.DecimalField('Оценка игры', decimal_places=1, max_digits=2, choices=choices)

    def __str__(self):
        return f"{self.user} {self.text}"

    def get_absolute_url(self):
        return reverse("game:game_slug", kwargs={"game_slug": self.game.slug})

homework30/store/game_store/forms.py
from .models import Comment

from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'grade')
        labels = {
            'text': 'Комментарий',
            'grade': 'Оценка Игры',
        }
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий'}),
            'grade': forms.Select(attrs={'class': 'form-control'}),
        }

homework30/store/game_store/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Avg
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Game, Category, Comment
from .forms import CommentForm


def games_all(request):
    games = Game.objects.filter(is_active=True).all()
    return render(request, 'games/home.html', {'games': games})


def every_game(request, game_slug):
    game = get_object_or_404(Game, slug=game_slug)
    comments = game.comments.all().order_by('-pub_date')
    average_grade = game.comments.aggregate(Avg('grade'))
    average_grade = average_grade['grade__avg']
    context = {
        'game': game,
        'comments': comments,
        'average_grade': average_grade,
    }
    return render(request, 'games/game.html', context=context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'category/all_categories.html', {'categories': categories})


from django.contrib import messages
def category_games(request, category_slug):
    if not request.user.is_authenticated:
        messages.info(request, 
            'Для просмотра игр в категории вы должны войти в систему или зарегистрироваться...'
        )
        return render(request, 'authenticate/log_reg.html')
    else:
        category = get_object_or_404(Category, slug=category_slug)
        games = category.game_set.filter(is_active=True).all()
        context = {
            'category': category,
            'games': games
        }
        return render(request, 'category/category_games.html', context)


def sorting_in_alphabetical_order(request):
    sorted_games = Game.objects.order_by('name').all()
    paginator = Paginator(sorted_games, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'sorting/sort_alphab.html', {'page_obj': page_obj})


def sorting_not_in_alphabetical_order(request):
    sorted_games = Game.objects.order_by('-name').all()
    paginator = Paginator(sorted_games, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'sorting/sort_alphab.html', {'page_obj': page_obj})


def search_games(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        games = Game.objects.filter(name__icontains=searched)
        return render(request, 'search/search_games.html', {'searched': searched, 'games': games})
    else:
        return render(request, 'search/search_games.html', {})


class CommentCreateView(CreateView, LoginRequiredMixin):
    template_name = 'forms/comment_create.html'
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.game = Game.objects.get(slug=self.kwargs['game_slug'])
        return super().form_valid(form)


class CommentUpdateView(UpdateView):
    model = Comment
    template_name = 'forms/comment_update.html'
    form_class = CommentForm


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'forms/comment_delete.html'
    success_url = reverse_lazy('game:games')

homework30/store/game_store/templates/games/game.html
{% extends  'game_store/base.html'%}
{% load static %}
{% block title %}{{game.name}}{% endblock %}

{% block content %}
<code>
    <div class="container my-5">
        <h1 class="fw-light">{{game.name}}</h1><br>
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <img class="rounded" style="width: 500px; height: 600px; object-fit: cover;" src={{game.game_image.url}} alt={{game.name}}/>
                <div>
                    <br>
                    <h5>{{game.name}}</h5><br>

                    {% if average_grade %}
                        <h6>Оценка игры: {{average_grade|floatformat:1}}</h6>
                    {% else %}
                        <h6>Оценки пока нет...</h6>
                    {% endif %}
                    
                    <strong>Жанры:</strong>
                    {{game.category}}<br>
                    <strong>Цена:</strong>
                    {{game.price}}
                    <strong>руб</strong><br>
                    <strong>Дата выхода:</strong>
                    {{game.release_date|date:"d F, Y."}}<hr>
                </div>
                <br>
                <strong><h5>Описание:</h5></strong>
                <p>{{game.description}}</p><hr>
                <a href="{% url 'game:comment_add' game_slug=game.slug %}" class="btn btn-outline-primary">Оставить комментарий</a><br/><br/>
                <h2>{{ comments.count }} Comments</h2>
                {% for comment in comments %}
                        <strong>{{comment.user}}</strong>
                        {{comment.text | linebreaks}}
                    {% if user.is_authenticated %}
                        <div class="card-footer text-muted">
                            {% if user == comment.user %}
                                <a href="{% url 'game:comment_update' comment.id %}" class="btn btn-outline-warning">Изменить комментарий</a>
                                |
                                <a href="{% url 'game:comment_delete' comment.id %}" class="btn btn-outline-warning">Удалить комментарий</a>
                            {% endif %}
                        </div><br/>
                    {% endif %}
                {% endfor %}
                <hr>
            </div>
        </div>
    </div>
</code>
{% endblock %}

homework30/store/game_store/templates/games/home.html
{% extends 'game_store/base.html' %}
{% load static %}
{% block title %}Games{% endblock %}

{% block content %}
<code>
    {% for game in games %}
            <img class="rounded" style="width: 400px; height: 400px; object-fit: cover;" src={{game.game_image.url}} alt="Name" />
            <br><br>
            <h5><a href="{% url 'game:game_slug' game_slug=game.slug %}">{{game.name}}</a></h5>
            <li>Жанр: {{game.category}}</li>
            <li>Цена: {{game.price}} руб</li>
            <li>Дата выхода: {{game.release_date|date:"d F, Y."}}</li>
            <hr>
    {% endfor %}
</code>
{% endblock %}